package com.sid.gl.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-03-10T19:37:35.813+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://service.gl.sid.com/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.GetCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.sid.gl.service.CustomerResponse getCustomer(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "customerList", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.CustomerList")
    @ResponseWrapper(localName = "customerListResponse", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.CustomerListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sid.gl.service.CustomerResponse> customerList()
;

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://service.gl.sid.com/", className = "com.sid.gl.service.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.sid.gl.service.CustomerResponse saveCustomer(

        @WebParam(name = "customer", targetNamespace = "")
        com.sid.gl.service.CustomerRequest customer
    );
}
